<?php
/**
 * @file
 * @copyright The Royal National Theatre
 * @author John-Paul Drawneek
 */

/**
 * Implements hook_menu().
 *
 * @return array
 *   Menu config
 */
function nt_assets_menu() {
  return array(
    'admin/config/system/finalcut' => array(
      'title'            => 'NT FinalCut server assets config',
      'description'      => t('Configures the FinalCut server asset paths.'),
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('nt_assets_finalcut'),
      'access arguments' => array('access content'),
    ),
  );
}
/**
 * Setting paths for FinalCut server assets
 *
 * @return array
 *   Form configure
 */
function nt_assets_finalcut() {
  $form = array(
    'finalcut_audio_directory' => array(
      '#type' => 'textarea',
      '#title' => t('Audio'),
      '#default_value' => variable_get('finalcut_audio_directory', 'http://video.nt-online.org/finalcut/audio_exports'),
      '#description' => t('Path to where audio files are stored on FinalCut web faceing server.'),
    ),
    'finalcut_image_directory' => array(
      '#type' => 'textarea',
      '#title' => t('Image'),
      '#default_value' => variable_get('finalcut_image_directory', 'http://video.nt-online.org/finalcut/image_exports'),
      '#description' => t('Path to where image files are stored on FinalCut web faceing server.'),
    ),
    'finalcut_video_directory' => array(
      '#type' => 'textarea',
      '#title' => t('Video'),
      '#default_value' => variable_get('finalcut_video_directory', 'http://video.nt-online.org/finalcut/video_exports'),
      '#description' => t('Path to where video files are stored on FinalCut web faceing server.'),
    ),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_stream_wrappers().
 *
 * @return array
 *   A nested array, keyed first by scheme name ("public" for "public://")
 */
function nt_assets_stream_wrappers() {
  return array(
    'finalcut-audio' => array(
      'name' => t('Final Cut Audio media'), 
      'class' => 'FinalCutAudioPublicStreamWrapper', 
      'description' => t('Final Cut Server media wrapper.'), 
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
    'finalcut-image' => array(
      'name' => t('Final Cut Image media'), 
      'class' => 'FinalCutImagePublicStreamWrapper', 
      'description' => t('Final Cut Server media wrapper.'), 
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
    'finalcut-video' => array(
      'name' => t('Final Cut Video media'), 
      'class' => 'FinalCutVideoPublicStreamWrapper', 
      'description' => t('Final Cut Server media wrapper.'), 
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}
