<?php
/**
 * @file
 * @copyright The Royal National Theatre
 * @author John-Paul Drawneek
 */

/**
 * Implements hook_node_info().
 */
function nt_rich_media_node_info() {
  return array(
    'nt_rich_media' => array(
      'type' => 'nt_rich_media',
      'name' => t('NT Rich Media node'),
      'base' => 'nt_rich_media',
      'description' => t('Create a node for an NT Rich Media like flash and embedded html content.'),
      'locked' => TRUE,
      'has_title' => TRUE,
    ),
  );
}
/**
 * Implements hook_menu().
 */
function nt_rich_media_menu() {
  return array();
}
/**
 * Implements hook_theme().
 */
function nt_rich_media_theme($existing, $type, $theme, $path) {
  return array();
}
/**
 * Implements hook_view().
 */
function nt_rich_media_view($node, $view_mode) {
  // create output field.
  drupal_alter('nt_rich_media_view_render', $node);
  return $node;
}
/**
 * Implements hook_form().
 */
function nt_rich_media_form($node, $form_state) {
  $form = node_content_form($node, $form_state);
  return $form;
}
