<?php
/**
 * @file
 * @copyright The Royal National Theatre
 * @author John-Paul Drawneek
 */

/**
 * Implements hook_menu().
 */
function nt_edge_suite_menu() {
  return array();
}
/**
 * Implements hook_theme().
 */
function nt_edge_suite_theme($existing, $type, $theme, $path) {
  return array();
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function nt_edge_suite_form_nt_rich_media_node_form_alter(&$form, &$form_state, $form_id) {

  $options = array('' => '---' . t('None') . '---');
  foreach (edge_suite_block_info() as $key => $block) {
    $options[$key] = $block['info'];
  }

  foreach ($form['nt_edge_suite_block'][LANGUAGE_NONE] as $i => &$item) {
    if (is_numeric($i)) {
      $item['value']['#type'] = 'select';
      $item['value']['#options'] = $options;
      $item['value']['#size'] = 1;
    }
  }
}
/**
 * Implements hook_node_view().
 */
function nt_edge_suite_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'rich_media' || $node->type == 'nt_rich_media') {
    nt_edge_suite_nt_rich_media_view_render_alter($node);
  }
}
/**
 * Implements hook_nt_rich_media_view_render_alter().
 */
function nt_edge_suite_nt_rich_media_view_render_alter(&$node) {
  if (isset($node->nt_edge_suite_block) && !empty($node->nt_edge_suite_block)) {
    $block = edge_suite_block_view(
      $node->nt_edge_suite_block[LANGUAGE_NONE][0]['value']
    );
    $node->content['nt_edge_suite_block'] = $block['content'];
    drupal_add_css(drupal_get_path('module', 'nt_edge_suite') . '/css/nt_edge_suite.css');
    $node->content['main_content'] = $block['content'];
  }
}
