<?php
/**
 * @file
 * @copyright The Royal National Theatre
 * @author John-Paul Drawneek
 */

/**
 * Implements hook_menu().
 *
 * @return array
 *   Menu config
 */
function nt_edge_suite_menu() {
  return array();
}
/**
 * Implements hook_theme().
 *
 * @param string $existing
 *   An array of existing implementations that may be used for override
 *   purposes.
 * @param string $type
 *   Whether a theme, module, etc. is being processed.
 * @param string $theme
 *   The actual name of theme, module, etc. that is being being processed.
 * @param string $path
 *   The directory path of the theme or module, so that it doesn't need to be
 *   looked up.
 *
 * @return array
 *   An associative array of theme hook information.
 */
function nt_edge_suite_theme($existing, $type, $theme, $path) {
  return array();
}
/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param array $form_state
 *   A keyed array containing the current state of the form.
 * @param string $form_id
 *   String representing the name of the form itself.
 */
function nt_edge_suite_form_rich_media_node_form_alter(&$form, &$form_state, $form_id) {

  $options = array('' => '---' . t('None') . '---');
  foreach (edge_suite_block_info() as $key => $block) {
    $options[$key] = $block['info'];
  }

  foreach ($form['nt_edge_suite_block'][LANGUAGE_NONE] as $i => &$item) {
    if (is_numeric($i)) {
      $item['value']['#type'] = 'select';
      $item['value']['#options'] = $options;
      $item['value']['#size'] = 1;
    }
  }
}
/**
 * Implements hook_node_view().
 *
 * @param stdClass $node
 *   The node that is being assembled for rendering.
 * @param string $view_mode
 *   The $view_mode parameter from node_view().
 * @param string $langcode
 *   The language code used for rendering.
 */
function nt_edge_suite_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'rich_media' || $node->type == 'nt_rich_media') {
    if (isset($node->nt_edge_suite_block) && !empty($node->nt_edge_suite_block)) {
      $block = edge_suite_block_view(
        $node->nt_edge_suite_block[LANGUAGE_NONE][0]['value']
      );
      $node->content['nt_edge_suite_block'] = $block['content'];
      drupal_add_css(drupal_get_path('module', 'nt_edge_suite') . '/css/nt_edge_suite.css');
    }
  }
}
